### ISSUE TITLE
Error when running sem_tables(fit)

### ISSUE THREAD

**Issue by over-soul** [dr-JT/semoutput#6] opened 2023-10-04 04:04 UTC
Hello,
I am getting this error:
```
> sem_tables(fit)
Error in if (x@call$se == "boot" | x@call$se == "bootstrap") { : 
  argument is of length zero
```
This is the full code:
```
# Specify the model parameters using intuitive syntax to write out equations
model <- ' visual  =~ x1 + x2 + x3 
              textual =~ x4 + x5 + x6
              speed   =~ x7 + x8 + x9 '

# Run a latent variable analysis
fit <- cfa(model, data = HolzingerSwineford1939, missing = "ML", std.lv = FALSE)

# Print styled tables
sem_tables(fit)
```

**Comment by dr-JT** [comment] 2023-10-05 17:20
Hi @over-soul! Yep I just ran into the same error. Thanks for pointing this out. It should be fixed now. 

It was caused by a small update I did for printing out certain warning messages.

**Closed as completed by dr-JT** 2023-10-05 17:20 UTC

**Comment by over-soul** [comment] 2023-10-05 22:09
Thank you for the wonderful package and thank you for fixing.
